const cityState = [
    //New York
    'New York,NY',
    'Buffalo,NY',
    'Rochester,NY',
    'Yonkers,NY',
    'Syracuse,NY',
    'Albany,NY',
    'New Rochelle,NY',
    'Mount Vernon,NY',
    'Schenectady,NY',
    'Utica,NY',
    'White Plains,NY',
    'Hempstead,NY',
    'Troy,NY',
    'Niagara Falls,NY',
    'Binghamton,NY',
    'Freeport,NY',
    'Valley Stream,NY',
    //California
    'Los Angeles,CA',
    'San Diego,CA',
    'San Jose,CA',
    'San Francisco,CA',
    'Fresno,CA',
    'Sacramento,CA',
    'Long Beach,CA',
    'Oakland,CA',
    'Bakersfield,CA',
    'Anaheim,CA',
    'Santa Ana,CA',
    'Riverside,CA',
    'Stockton,CA',
    'Chula Vista,CA',
    'Irvine,CA',
    'Fremont,CA',
    'San Bernardino,CA',
    'Modesto,CA',
    'Fontana,CA',
    'Oxnard,CA',
    'Moreno Valley,CA',
    'Huntington Beach,CA',
    'Glendale,CA',
    'Santa Clarita,CA',
    'Garden Grove,CA',
    'Oceanside,CA',
    'Rancho Cucamonga,CA',
    'Santa Rosa,CA',
    'Ontario,CA',
    'Lancaster,CA',
    'Elk Grove,CA',
    'Corona,CA',
    'Palmdale,CA',
    'Salinas,CA',
    'Pomona,CA',
    'Hayward,CA',
    'Escondido,CA',
    'Torrance,CA',
    'Sunnyvale,CA',
    'Orange,CA',
    'Fullerton,CA',
    'Pasadena,CA',
    'Thousand Oaks,CA',
    'Visalia,CA',
    'Simi Valley,CA',
    'Concord,CA',
    'Roseville,CA',
    'Victorville,CA',
    'Santa Clara,CA',
    'Vallejo,CA',
    'Berkeley,CA',
    'El Monte,CA',
    'Downey,CA',
    'Costa Mesa,CA',
    'Inglewood,CA',
    'Carlsbad,CA',
    'San Buenaventura,CA',
    'Fairfield,CA',
    'West Covina,CA',
    'Murrieta,CA',
    'Richmond,CA',
    'Norwalk,CA',
    'Antioch,CA',
    'Temecula,CA',
    'Burbank,CA',
    'Daly City,CA',
    'Rialto,CA',
    'Santa Maria,CA',
    'El Cajon,CA',
    'San Mateo,CA',
    'Clovis,CA',
    'Compton,CA',
    'Jurupa Valley,CA',
    'Vista,CA',
    'South Gate,CA',
    'Mission Viejo,CA',
    'Vacaville,CA',
    'Carson,CA',
    'Hesperia,CA',
    'Santa Monica,CA',
    'Westminster,CA',
    'Redding,CA',
    'Santa Barbara,CA',
    'Chico,CA',
    'Newport Beach,CA',
    'San Leandro,CA',
    'San Marcos,CA',
    'Whittier,CA',
    'Hawthorne,CA',
    'Citrus Heights,CA',
    'Tracy,CA',
    'Alhambra,CA',
    'Livermore,CA',
    'Buena Park,CA',
    'Menifee,CA',
    'Hemet,CA',
    'Lakewood,CA',
    'Merced,CA',
    'Chino,CA',
    'Indio,CA',
    'Redwood City,CA',
    'Lake Forest,CA',
    'Napa,CA',
    'Tustin,CA',
    'Bellflower,CA',
    'Mountain View,CA',
    'Chino Hills,CA',
    'Baldwin Park,CA',
    'Alameda,CA',
    'Upland,CA',
    'San Ramon,CA',
    'Folsom,CA',
    'Pleasanton,CA',
    'Union City,CA',
    'Perris,CA',
    'Manteca,CA',
    'Lynwood,CA',
    'Apple Valley,CA',
    'Redlands,CA',
    'Turlock,CA',
    'Milpitas,CA',
    'Redondo Beach,CA',
    'Rancho Cordova,CA',
    'Yorba Linda,CA',
    'Palo Alto,CA',
    'Davis,CA',
    'Camarillo,CA',
    'Walnut Creek,CA',
    'Pittsburg,CA',
    'South San Francisco,CA',
    'Yuba City,CA',
    'San Clemente,CA',
    'Laguna Niguel,CA',
    'Pico Rivera,CA',
    'Montebello,CA',
    'Lodi,CA',
    'Madera,CA',
    'Santa Cruz,CA',
    'La Habra,CA',
    'Encinitas,CA',
    'Monterey Park,CA',
    'Tulare,CA',
    'Cupertino,CA',
    'Gardena,CA',
    'National City,CA',
    'Rocklin,CA',
    'Petaluma,CA',
    'Huntington Park,CA',
    'San Rafael,CA',
    'La Mesa,CA',
    'Arcadia,CA',
    'Fountain Valley,CA',
    'Diamond Bar,CA',
    'Woodland,CA',
    'Santee,CA',
    'Lake Elsinore,CA',
    'Porterville,CA',
    'Paramount,CA',
    'Eastvale,CA',
    'Rosemead,CA',
    'Hanford,CA',
    'Highland,CA',
    'Brentwood,CA',
    'Novato,CA',
    'Colton,CA',
    'Cathedral City,CA',
    'Delano,CA',
    'Yucaipa,CA',
    'Watsonville,CA',
    'Placentia,CA',
    'Glendora,CA',
    'Gilroy,CA',
    'Palm Desert,CA',
    'Cerritos,CA',
    'West Sacramento,CA',
    'Aliso Viejo,CA',
    'Poway,CA',
    'La Mirada,CA',
    'Rancho Santa Margarita,CA',
    'Cypress,CA',
    'Dublin,CA',
    'Covina,CA',
    'Azusa,CA',
    'Palm Springs,CA',
    'San Luis Obispo,CA',
    'Ceres,CA',
    'San Jacinto,CA',
    'Lincoln,CA',
    'Newark,CA',
    'Lompoc,CA',
    'El Centro,CA',
    'Danville,CA',
    'Bell Gardens,CA',
    'Coachella,CA',
    'Rancho Palos Verdes,CA',
    'San Bruno,CA',
    'Rohnert Park,CA',
    'Brea,CA',
    'La Puente,CA',
    'Campbell,CA',
    'San Gabriel,CA',
    'Beaumont,CA',
    'Morgan Hill,CA',
    'Culver City,CA',
    'Calexico,CA',
    'Stanton,CA',
    'La Quinta,CA',
    'Pacifica,CA',
    'Montclair,CA',
    'Oakley,CA',
    'Monrovia,CA',
    'Los Banos,CA',
    'Martinez,CA',
    //Illinois
    'Chicago,IL',
    'Aurora,IL',
    'Rockford,IL',
    'Joliet,IL',
    'Naperville,IL',
    'Springfield,IL',
    'Peoria,IL',
    'Elgin,IL',
    'Waukegan,IL',
    'Cicero,IL',
    'Champaign,IL',
    'Bloomington,IL',
    'Arlington Heights,IL',
    'Evanston,IL',
    'Decatur,IL',
    'Schaumburg,IL',
    'Bolingbrook,IL',
    'Palatine,IL',
    'Skokie,IL',
    'Des Plaines,IL',
    'Orland Park,IL',
    'Tinley Park,IL',
    'Oak Lawn,IL',
    'Berwyn,IL',
    'Mount Prospect,IL',
    'Normal,IL',
    'Wheaton,IL',
    'Hoffman Estates,IL',
    'Oak Park,IL',
    'Downers Grove,IL',
    'Elmhurst,IL',
    'Glenview,IL',
    'DeKalb,IL',
    'Lombard,IL',
    'Belleville,IL',
    'Moline,IL',
    'Buffalo Grove,IL',
    'Bartlett,IL',
    'Urbana,IL',
    'Quincy,IL',
    'Crystal Lake,IL',
    'Plainfield,IL',
    'Streamwood,IL',
    'Carol Stream,IL',
    'Romeoville,IL',
    'Rock Island,IL',
    'Hanover Park,IL',
    'Carpentersville,IL',
    'Wheeling,IL',
    'Park Ridge,IL',
    'Addison,IL',
    'Calumet City,IL',
    //Texas
    'Houston,TX',
    'San Antonio,TX',
    'Dallas,TX',
    'Austin,TX',
    'Fort Worth,TX',
    'El Paso,TX',
    'Arlington,TX',
    'Corpus Christi,TX',
    'Plano,TX',
    'Laredo,TX',
    'Lubbock,TX',
    'Garland,TX',
    'Irving,TX',
    'Amarillo,TX',
    'Grand Prairie,TX',
    'Brownsville,TX',
    'Pasadena,TX',
    'McKinney,TX',
    'Mesquite,TX',
    'McAllen,TX',
    'Killeen,TX',
    'Frisco,TX',
    'Waco,TX',
    'Carrollton,TX',
    'Denton,TX',
    'Midland,TX',
    'Abilene,TX',
    'Beaumont,TX',
    'Round Rock,TX',
    'Odessa,TX',
    'Wichita Falls,TX',
    'Richardson,TX',
    'Lewisville,TX',
    'Tyler,TX',
    'College Station,TX',
    'Pearland,TX',
    'San Angelo,TX',
    'Allen,TX',
    'League City,TX',
    'Sugar Land,TX',
    'Longview,TX',
    'Edinburg,TX',
    'Mission,TX',
    'Bryan,TX',
    'Baytown,TX',
    'Pharr,TX',
    'Temple,TX',
    'Missouri City,TX',
    'Flower Mound,TX',
    'Harlingen,TX',
    'North Richland Hills,TX',
    'Victoria,TX',
    'Conroe,TX',
    'New Braunfels,TX',
    'Mansfield,TX',
    'Cedar Park,TX',
    'Rowlett,TX',
    'Port Arthur,TX',
    'Euless,TX',
    'Georgetown,TX',
    'Pflugerville,TX',
    'DeSoto,TX',
    'San Marcos,TX',
    'Grapevine,TX',
    'Bedford,TX',
    'Galveston,TX',
    'Cedar Hill,TX',
    'Texas City,TX',
    'Wylie,TX',
    'Haltom City,TX',
    'Keller,TX',
    'Coppell,TX',
    'Rockwall,TX',
    'Huntsville,TX',
    'Duncanville,TX',
    'Sherman,TX',
    'The Colony,TX',
    'Burleson,TX',
    'Hurst,TX',
    'Lancaster,TX',
    'Texarkana,TX',
    'Friendswood,TX',
    'Weslaco,TX',
    //Pennsylvania
    'Philadelphia,PA',
    'Pittsburgh,PA',
    'Allentown,PA',
    'Erie,PA',
    'Reading,PA',
    'Scranton,PA',
    'Bethlehem,PA',
    'Lancaster,PA',
    'Harrisburg,PA',
    'Altoona,PA',
    'York,PA',
    'State College,PA',
    'Wilkes-Barre,PA',
    //Arizona
    'Phoenix,AZ',
    'Tucson,AZ',
    'Mesa,AZ',
    'Chandler,AZ',
    'Glendale,AZ',
    'Scottsdale,AZ',
    'Gilbert,AZ',
    'Tempe,AZ',
    'Peoria,AZ',
    'Surprise,AZ',
    'Yuma,AZ',
    'Avondale,AZ',
    'Goodyear,AZ',
    'Flagstaff,AZ',
    'Buckeye,AZ',
    'Lake Havasu City,AZ',
    'Casa Grande,AZ',
    'Sierra Vista,AZ',
    'Maricopa,AZ',
    'Oro Valley,AZ',
    'Prescott,AZ',
    'Bullhead City,AZ',
    'Prescott Valley,AZ',
    'Marana,AZ',
    'Apache Junction,AZ',
    //Florida
    'Jacksonville,FL',
    'Miami,FL',
    'Tampa,FL',
    'Orlando,FL',
    'St Petersburg,FL',
    'Hialeah,FL',
    'Tallahassee,FL',
    'Fort Lauderdale,FL',
    'Port St Lucie,FL',
    'Cape Coral,FL',
    'Pembroke Pines,FL',
    'Hollywood,FL',
    'Miramar,FL',
    'Gainesville,FL',
    'Coral Springs,FL',
    'Miami Gardens,FL',
    'Clearwater,FL',
    'Palm Bay,FL',
    'Pompano Beach,FL',
    'West Palm Beach,FL',
    'Lakeland,FL',
    'Davie,FL',
    'Miami Beach,FL',
    'Sunrise,FL',
    'Plantation,FL',
    'Boca Raton,FL',
    'Deltona,FL',
    'Largo,FL',
    'Deerfield Beach,FL',
    'Palm Coast,FL',
    'Melbourne,FL',
    'Boynton Beach,FL',
    'Lauderhill,FL',
    'Weston,FL',
    'Fort Myers,FL',
    'Kissimmee,FL',
    'Homestead,FL',
    'Tamarac,FL',
    'Delray Beach,FL',
    'Daytona Beach,FL',
    'North Miami,FL',
    'Wellington,FL',
    'North Port,FL',
    'Jupiter,FL',
    'Ocala,FL',
    'Port Orange,FL',
    'Margate,FL',
    'Coconut Creek,FL',
    'Sanford,FL',
    'Sarasota,FL',
    'Pensacola,FL',
    'Bradenton,FL',
    'Palm Beach Gardens,FL',
    'Pinellas Park,FL',
    'Coral Gables,FL',
    'Doral,FL',
    'Bonita Springs,FL',
    'Apopka,FL',
    'Titusville,FL',
    'North Miami Beach,FL',
    'Oakland Park,FL',
    'Fort Pierce,FL',
    'North Lauderdale,FL',
    'Cutler Bay,FL',
    'Altamonte Springs,FL',
    'St Cloud,FL',
    'Greenacres,FL',
    'Ormond Beach,FL',
    'Ocoee,FL',
    'Hallandale Beach,FL',
    'Winter Garden,FL',
    'Aventura,FL',
    //Indiana
    'Indianapolis,IN',
    'Fort Wayne,IN',
    'Evansville,IN',
    'South Bend,IN',
    'Carmel,IN',
    'Bloomington,IN',
    'Fishers,IN',
    'Hammond,IN',
    'Gary,IN',
    'Muncie,IN',
    'Lafayette,IN',
    'Terre Haute,IN',
    'Kokomo,IN',
    'Anderson,IN',
    'Noblesville,IN',
    'Greenwood,IN',
    'Elkhart,IN',
    'Mishawaka,IN',
    'Lawrence,IN',
    'Jeffersonville,IN',
    'Columbus,IN',
    'Portage,IN',
    //Ohio
    'Columbus,OH',
    'Cleveland,OH',
    'Cincinnati,OH',
    'Toledo,OH',
    'Akron,OH',
    'Dayton,OH',
    'Parma,OH',
    'Canton,OH',
    'Youngstown,OH',
    'Lorain,OH',
    'Hamilton,OH',
    'Springfield,OH',
    'Kettering,OH',
    'Elyria,OH',
    'Lakewood,OH',
    'Cuyahoga Falls,OH',
    'Middletown,OH',
    'Euclid,OH',
    'Newark,OH',
    'Mansfield,OH',
    'Mentor,OH',
    'Beavercreek,OH',
    'Cleveland Heights,OH',
    'Strongsville,OH',
    'Dublin,OH',
    'Fairfield,OH',
    'Findlay,OH',
    'Warren,OH',
    'Lancaster,OH',
    'Lima,OH',
    'Huber Heights,OH',
    'Westerville,OH',
    'Marion,OH',
    'Grove City,OH',
    //North Carolina
    'Charlotte,NC',
    'Raleigh,NC',
    'Greensboro,NC',
    'Durham,NC',
    'Winston Salem,NC',
    'Fayetteville,NC',
    'Cary,NC',
    'Wilmington,NC',
    'High Point,NC',
    'Greenville,NC',
    'Asheville,NC',
    'Concord,NC',
    'Gastonia,NC',
    'Jacksonville,NC',
    'Chapel Hill,NC',
    'Rocky Mount,NC',
    'Burlington,NC',
    'Wilson,NC',
    'Huntersville,NC',
    'Kannapolis,NC',
    'Apex,NC',
    'Hickory,NC',
    'Goldsboro,NC',
    //Michigan
    'Detroit,MI',
    'Grand Rapids,MI',
    'Warren,MI',
    'Sterling Heights,MI',
    'Ann Arbor,MI',
    'Lansing,MI',
    'Flint,MI',
    'Dearborn,MI',
    'Livonia,MI',
    'Westland,MI',
    'Troy,MI',
    'Farmington Hills,MI',
    'Kalamazoo,MI',
    'Wyoming,MI',
    'Southfield,MI',
    'Rochester Hills,MI',
    'Taylor,MI',
    'Pontiac,MI',
    'St Clair Shores,MI',
    'Royal Oak,MI',
    'Novi,MI',
    'Dearborn Heights,MI',
    'Battle Creek,MI',
    'Saginaw,MI',
    'Kentwood,MI',
    'East Lansing,MI',
    'Roseville,MI',
    'Portage,MI',
    'Midland,MI',
    'Lincoln Park,MI',
    'Muskegon,MI',
    //Tennessee
    'Memphis,TN',
    'Nashville,TN',
    'Knoxville,TN',
    'Chattanooga,TN',
    'Clarksville,TN',
    'Murfreesboro,TN',
    'Jackson,TN',
    'Franklin,TN',
    'Johnson City,TN',
    'Bartlett,TN',
    'Hendersonville,TN',
    'Kingsport,TN',
    'Collierville,TN',
    'Cleveland,TN',
    'Smyrna,TN',
    'Germantown,TN',
    'Brentwood,TN',
    //Massachusetts
    'Boston,MA',
    'Worcester,MA',
    'Springfield,MA',
    'Lowell,MA',
    'Cambridge,MA',
    'New Bedford,MA',
    'Brockton,MA',
    'Quincy,MA',
    'Lynn,MA',
    'Fall River,MA',
    'Newton,MA',
    'Lawrence,MA',
    'Somerville,MA',
    'Waltham,MA',
    'Haverhill,MA',
    'Malden,MA',
    'Medford,MA',
    'Taunton,MA',
    'Chicopee,MA',
    'Weymouth Town,MA',
    'Revere,MA',
    'Peabody,MA',
    'Methuen,MA',
    'Barnstable Town,MA',
    'Pittsfield,MA',
    'Attleboro,MA',
    'Everett,MA',
    'Salem,MA',
    'Westfield,MA',
    'Leominster,MA',
    'Fitchburg,MA',
    'Beverly,MA',
    'Holyoke,MA',
    'Marlborough,MA',
    'Woburn,MA',
    'Chelsea,MA',
    //Washington
    'Seattle,WA',
    'Spokane,WA',
    'Tacoma,WA',
    'Vancouver,WA',
    'Bellevue,WA',
    'Kent,WA',
    'Everett,WA',
    'Renton,WA',
    'Yakima,WA',
    'Federal Way,WA',
    'Spokane Valley,WA',
    'Bellingham,WA',
    'Kennewick,WA',
    'Auburn,WA',
    'Pasco,WA',
    'Marysville,WA',
    'Lakewood,WA',
    'Redmond,WA',
    'Shoreline,WA',
    'Richland,WA',
    'Kirkland,WA',
    'Burien,WA',
    'Sammamish,WA',
    'Olympia,WA',
    'Lacey,WA',
    'Edmonds,WA',
    'Bremerton,WA',
    'Puyallup,WA',
    //Colorado
    'Denver,CO',
    'Colorado Springs,CO',
    'Aurora,CO',
    'Fort Collins,CO',
    'Lakewood,CO',
    'Thornton,CO',
    'Arvada,CO',
    'Westminster,CO',
    'Pueblo,CO',
    'Centennial,CO',
    'Boulder,CO',
    'Greeley,CO',
    'Longmont,CO',
    'Loveland,CO',
    'Grand Junction,CO',
    'Broomfield,CO',
    'Castle Rock,CO',
    'Commerce City,CO',
    'Parker,CO',
    'Littleton,CO',
    'Northglenn,CO',
    //District of Columbia
    'Washington,DC',
    //Maryland
    'Baltimore,MD',
    'Frederick,MD',
    'Rockville,MD',
    'Gaithersburg,MD',
    'Bowie,MD',
    'Hagerstown,MD',
    'Annapolis,MD',
    //Kentucky
    'Louisville,KY',
    'Lexington,KY',
    'Bowling Green,KY',
    'Owensboro,KY',
    'Covington,KY',
    //Oregon
    'Portland,OR',
    'Eugene,OR',
    'Salem,OR',
    'Gresham,OR',
    'Hillsboro,OR',
    'Beaverton,OR',
    'Bend,OR',
    'Medford,OR',
    'Springfield,OR',
    'Corvallis,OR',
    'Albany,OR',
    'Tigard,OR',
    'Lake Oswego,OR',
    'Keizer,OR',
    //Oklahoma
    'Oklahoma City,OK',
    'Tulsa,OK',
    'Norman,OK',
    'Broken Arrow,OK',
    'Lawton,OK',
    'Edmond,OK',
    'Moore,OK',
    'Midwest City,OK',
    'Enid,OK',
    'Stillwater,OK',
    'Muskogee,OK',
    //Wisconsin
    'Milwaukee,WI',
    'Madison,WI',
    'Green Bay,WI',
    'Kenosha,WI',
    'Racine,WI',
    'Appleton,WI',
    'Waukesha,WI',
    'Eau Claire,WI',
    'Oshkosh,WI',
    'Janesville,WI',
    'West Allis,WI',
    'La Crosse,WI',
    'Sheboygan,WI',
    'Wauwatosa,WI',
    'Fond du Lac,WI',
    'New Berlin,WI',
    'Wausau,WI',
    'Brookfield,WI',
    'Greenfield,WI',
    'Beloit,WI',
    //Nevada
    'Las Vegas,NV',
    'Henderson,NV',
    'Reno,NV',
    'North Las Vegas,NV',
    'Sparks,NV',
    'Carson City,NV',
    //New Mexico
    'Albuquerque,NM',
    'Las Cruces,NM',
    'Rio Rancho,NM',
    'Santa Fe,NM',
    'Roswell,NM',
    'Farmington,NM',
    'Clovis,NM',
    //Missouri
    'Kansas City,MO',
    'St.Louis,MO',
    'Springfield,MO',
    'Independence,MO',
    'Columbia,MO',
    'Lees Summit,MO',
    'O Fallon,MO',
    'St Joseph,MO',
    'St Charles,MO',
    'St Peters,MO',
    'Blue Springs,MO',
    'Florissant,MO',
    'Joplin,MO',
    'Chesterfield,MO',
    'Jefferson City,MO',
    'Cape Girardeau,MO',
    //Virginia
    'Virginia Beach,VA',
    'Norfolk,VA',
    'Chesapeake,VA',
    'Richmond,VA',
    'Newport News,VA',
    'Alexandria,VA',
    'Hampton,VA',
    'Roanoke,VA',
    'Portsmouth,VA',
    'Suffolk,VA',
    'Lynchburg,VA',
    'Harrisonburg,VA',
    'Leesburg,VA',
    'Charlottesville,VA',
    'Danville,VA',
    'Blacksburg,VA',
    'Manassas,VA',
    //Georgia
    'Atlanta,GA',
    'Columbus,GA',
    'Augusta,GA',
    'Savannah,GA',
    'Athens,GA',
    'Sandy Springs,GA',
    'Roswell,GA',
    'Macon,GA',
    'Johns Creek,GA',
    'Albany,GA',
    'Warner Robins,GA',
    'Alpharetta,GA',
    'Marietta,GA',
    'Valdosta,GA',
    'Smyrna,GA',
    'Dunwoody,GA',
    //Nebraska
    'Omaha,NE',
    'Lincoln,NE',
    'Bellevue,NE',
    'Grand Island,NE',
    //Minnesota
    'Minneapolis,MN',
    'St Paul,MN',
    'Rochester,MN',
    'Duluth,MN',
    'Bloomington,MN',
    'Brooklyn Park,MN',
    'Plymouth,MN',
    'St Cloud,MN',
    'Eagan,MN',
    'Woodbury,MN',
    'Maple Grove,MN',
    'Eden Prairie,MN',
    'Coon Rapids,MN',
    'Burnsville,MN',
    'Blaine,MN',
    'Lakeville,MN',
    'Minnetonka,MN',
    'Apple Valley,MN',
    'Edina,MN',
    'St Louis Park,MN',
    'Mankato,MN',
    'Maplewood,MN',
    'Moorhead,MN',
    'Shakopee,MN',
    //Kansas
    'Wichita,KS',
    'Overland Park,KS',
    'Kansas City,KS',
    'Olathe,KS',
    'Topeka,KS',
    'Lawrence,KS',
    'Shawnee,KS',
    'Manhattan,KS',
    'Lenexa,KS',
    'Salina,KS',
    'Hutchinson,KS',
    //Louisiana
    'New Orleans,LA',
    'Baton Rouge,LA',
    'Shreveport,LA',
    'Lafayette,LA',
    'Lake Charles,LA',
    'Kenner,LA',
    'Bossier City,LA',
    'Monroe,LA',
    'Alexandria,LA',
    //Hawaii
    'Honolulu,HI',
    //Alaska
    'Anchorage,AK',
    //New Jersey
    'Newark,NJ',
    'Jersey City,NJ',
    'Paterson,NJ',
    'Elizabeth,NJ',
    'Clifton,NJ',
    'Trenton,NJ',
    'Camden,NJ',
    'Passaic,NJ',
    'Union City,NJ',
    'Bayonne,NJ',
    'East Orange,NJ',
    'Vineland,NJ',
    'New Brunswick,NJ',
    'Hoboken,NJ',
    'Perth Amboy,NJ',
    'West New York,NJ',
    'Plainfield,NJ',
    'Hackensack,NJ',
    'Sayreville,NJ',
    'Kearny,NJ',
    'Linden,NJ',
    'Atlantic City,NJ',
    //Idaho
    'Boise City,ID',
    'Nampa,ID',
    'Meridian,ID',
    'Idaho Falls,ID',
    'Pocatello,ID',
    'Caldwell,ID',
    'Coeur d Alene,ID',
    'Twin Falls,ID',
    //Alabama
    'Birmingham,AL',
    'Montgomery,AL',
    'Mobile,AL',
    'Huntsville,AL',
    'Tuscaloosa,AL',
    'Hoover,AL',
    'Dothan,AL',
    'Auburn,AL',
    'Decatur,AL',
    'Madison,AL',
    'Florence,AL',
    'Gadsden,AL',
    //Iowa
    'Des Moines,IA',
    'Cedar Rapids,IA',
    'Davenport,IA',
    'Sioux City,IA',
    'Iowa City,IA',
    'Waterloo,IA',
    'Council Bluffs,IA',
    'Ames,IA',
    'West Des Moines,IA',
    'Dubuque,IA',
    'Ankeny,IA',
    'Urbandale,IA',
    'Cedar Falls,IA',
    //Arkansas
    'Little Rock,AR',
    'Fort Smith,AR',
    'Fayetteville,AR',
    'Springdale,AR',
    'Jonesboro,AR',
    'North Little Rock,AR',
    'Conway,AR',
    'Rogers,AR',
    'Pine Bluff,AR',
    'Bentonville,AR',
    //Utah
    'Salt Lake City,UT',
    'West Valley City,UT',
    'Provo,UT',
    'West Jordan,UT',
    'Orem,UT',
    'Sandy,UT',
    'Ogden,UT',
    'St George,UT',
    'Layton,UT',
    'Taylorsville,UT',
    'South Jordan,UT',
    'Lehi,UT',
    'Logan,UT',
    'Murray,UT',
    'Draper,UT',
    'Bountiful,UT',
    'Riverton,UT',
    'Roy,UT',
    //Rhode Island
    'Providence,RI',
    'Warwick,RI',
    'Cranston,RI',
    'Pawtucket,RI',
    'East Providence,RI',
    'Woonsocket,RI',
    //Mississippi
    'Jackson,MS',
    'Gulfport,MS',
    'Southaven,MS',
    'Hattiesburg,MS',
    'Biloxi,MS',
    'Meridian,MS',
    //South Dakota
    'Sioux Falls,SD',
    'Rapid City,SD',
    //Connecticut
    'Bridgeport,CT',
    'New Haven,CT',
    'Stamford,CT',
    'Hartford,CT',
    'Waterbury,CT',
    'Norwalk,CT',
    'Danbury,CT',
    'New Britain,CT',
    'Meriden,CT',
    'Bristol,CT',
    'West Haven,CT',
    'Milford,CT',
    'Middletown,CT',
    'Norwich,CT',
    'Shelton,CT',
    //South Carolina
    'Columbia,SC',
    'Charleston,SC',
    'North Charleston,SC',
    'Mount Pleasant,SC',
    'Rock Hill,SC',
    'Greenville,SC',
    'Summerville,SC',
    'Sumter,SC',
    'Goose Creek,SC',
    'Hilton Head Island,SC',
    'Florence,SC',
    'Spartanburg,SC',
    //New Hampshire
    'Manchester,NH',
    'Nashua,NH',
    'Concord,NH',
    //North Dakota
    'Fargo,ND',
    'Bismarck,ND',
    'Grand Forks,ND',
    'Minot,ND',
    //Montana
    'Billings,MT',
    'Missoula,MT',
    'Great Falls,MT',
    'Bozeman,MT',
    //Delaware
    'Wilmington,DE',
    'Dover,DE',
    //Maine
    'Portland,ME',
    //Wyoming
    'Cheyenne,WY',
    'Casper,WY',
    //West Virginia
    'Charleston,WV',
    'Huntington,WV',
    //Vermont
    'Burlington,VT'
];

const states = [
    'AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY'
]
// const states = [
//     'Alabama',
//     'Alaska',
//     'Arizona',
//     'Arkansas',
//     'California',
//     'Colorado',
//     'Connecticut',
//     'Delaware',
//     'Florida',
//     'Georgia',
//     'Hawaii',
//     'Idaho',
//     'Illinois',
//     'Indiana',
//     'Iowa',
//     'Kansas',
//     'Kentucky',
//     'Louisiana',
//     'Maine',
//     'Maryland',
//     'Massachusetts',
//     'Michigan',
//     'Minnesota',
//     'Mississippi',
//     'Missouri',
//     'Montana',
//     'Nebraska',
//     'Nevada',
//     'New Hampshire',
//     'New Jersey',
//     'New Mexico',
//     'New York',
//     'North Carolina',
//     'North Dakota',
//     'Ohio',
//     'Oklahoma',
//     'Oregon',
//     'Pennsylvania',
//     'Rhode Island',
//     'South Carolina',
//     'South Dakota',
//     'Tennessee',
//     'Texas',
//     'Utah',
//     'Vermont',
//     'Virginia',
//     'Washington',
//     'West Virginia',
//     'Wisconsin',
//     'Wyoming',
// ]

const cities = [
    //New York
    'New York',
    'Buffalo',
    'Rochester',
    'Yonkers',
    'Syracuse',
    'Albany',
    'New Rochelle',
    'Mount Vernon',
    'Schenectady',
    'Utica',
    'White Plains',
    'Hempstead',
    'Troy',
    'Niagara Falls',
    'Binghamton',
    'Freeport',
    'Valley Stream',
    //California
    'Los Angeles',
    'San Diego',
    'San Jose',
    'San Francisco',
    'Fresno',
    'Sacramento',
    'Long Beach',
    'Oakland',
    'Bakersfield',
    'Anaheim',
    'Santa Ana',
    'Riverside',
    'Stockton',
    'Chula Vista',
    'Irvine',
    'Fremont',
    'San Bernardino',
    'Modesto',
    'Fontana',
    'Oxnard',
    'Moreno Valley',
    'Huntington Beach',
    'Glendale',
    'Santa Clarita',
    'Garden Grove',
    'Oceanside',
    'Rancho Cucamonga',
    'Santa Rosa',
    'Ontario',
    'Lancaster',
    'Elk Grove',
    'Corona',
    'Palmdale',
    'Salinas',
    'Pomona',
    'Hayward',
    'Escondido',
    'Torrance',
    'Sunnyvale',
    'Orange',
    'Fullerton',
    'Pasadena',
    'Thousand Oaks',
    'Visalia',
    'Simi Valley',
    'Concord',
    'Roseville',
    'Victorville',
    'Santa Clara',
    'Vallejo',
    'Berkeley',
    'El Monte',
    'Downey',
    'Costa Mesa',
    'Inglewood',
    'Carlsbad',
    'San Buenaventura',
    'Fairfield',
    'West Covina',
    'Murrieta',
    'Richmond',
    'Norwalk',
    'Antioch',
    'Temecula',
    'Burbank',
    'Daly City',
    'Rialto',
    'Santa Maria',
    'El Cajon',
    'San Mateo',
    'Clovis',
    'Compton',
    'Jurupa Valley',
    'Vista',
    'South Gate',
    'Mission Viejo',
    'Vacaville',
    'Carson',
    'Hesperia',
    'Santa Monica',
    'Westminster',
    'Redding',
    'Santa Barbara',
    'Chico',
    'Newport Beach',
    'San Leandro',
    'San Marcos',
    'Whittier',
    'Hawthorne',
    'Citrus Heights',
    'Tracy',
    'Alhambra',
    'Livermore',
    'Buena Park',
    'Menifee',
    'Hemet',
    'Lakewood',
    'Merced',
    'Chino',
    'Indio',
    'Redwood City',
    'Lake Forest',
    'Napa',
    'Tustin',
    'Bellflower',
    'Mountain View',
    'Chino Hills',
    'Baldwin Park',
    'Alameda',
    'Upland',
    'San Ramon',
    'Folsom',
    'Pleasanton',
    'Union City',
    'Perris',
    'Manteca',
    'Lynwood',
    'Apple Valley',
    'Redlands',
    'Turlock',
    'Milpitas',
    'Redondo Beach',
    'Rancho Cordova',
    'Yorba Linda',
    'Palo Alto',
    'Davis',
    'Camarillo',
    'Walnut Creek',
    'Pittsburg',
    'South San Francisco',
    'Yuba City',
    'San Clemente',
    'Laguna Niguel',
    'Pico Rivera',
    'Montebello',
    'Lodi',
    'Madera',
    'Santa Cruz',
    'La Habra',
    'Encinitas',
    'Monterey Park',
    'Tulare',
    'Cupertino',
    'Gardena',
    'National City',
    'Rocklin',
    'Petaluma',
    'Huntington Park',
    'San Rafael',
    'La Mesa',
    'Arcadia',
    'Fountain Valley',
    'Diamond Bar',
    'Woodland',
    'Santee',
    'Lake Elsinore',
    'Porterville',
    'Paramount',
    'Eastvale',
    'Rosemead',
    'Hanford',
    'Highland',
    'Brentwood',
    'Novato',
    'Colton',
    'Cathedral City',
    'Delano',
    'Yucaipa',
    'Watsonville',
    'Placentia',
    'Glendora',
    'Gilroy',
    'Palm Desert',
    'Cerritos',
    'West Sacramento',
    'Aliso Viejo',
    'Poway',
    'La Mirada',
    'Rancho Santa Margarita',
    'Cypress',
    'Dublin',
    'Covina',
    'Azusa',
    'Palm Springs',
    'San Luis Obispo',
    'Ceres',
    'San Jacinto',
    'Lincoln',
    'Newark',
    'Lompoc',
    'El Centro',
    'Danville',
    'Bell Gardens',
    'Coachella',
    'Rancho Palos Verdes',
    'San Bruno',
    'Rohnert Park',
    'Brea',
    'La Puente',
    'Campbell',
    'San Gabriel',
    'Beaumont',
    'Morgan Hill',
    'Culver City',
    'Calexico',
    'Stanton',
    'La Quinta',
    'Pacifica',
    'Montclair',
    'Oakley',
    'Monrovia',
    'Los Banos',
    'Martinez',
    //Illinois
    'Chicago',
    'Aurora',
    'Rockford',
    'Joliet',
    'Naperville',
    'Springfield',
    'Peoria',
    'Elgin',
    'Waukegan',
    'Cicero',
    'Champaign',
    'Bloomington',
    'Arlington Heights',
    'Evanston',
    'Decatur',
    'Schaumburg',
    'Bolingbrook',
    'Palatine',
    'Skokie',
    'Des Plaines',
    'Orland Park',
    'Tinley Park',
    'Oak Lawn',
    'Berwyn',
    'Mount Prospect',
    'Normal',
    'Wheaton',
    'Hoffman Estates',
    'Oak Park',
    'Downers Grove',
    'Elmhurst',
    'Glenview',
    'DeKalb',
    'Lombard',
    'Belleville',
    'Moline',
    'Buffalo Grove',
    'Bartlett',
    'Urbana',
    'Quincy',
    'Crystal Lake',
    'Plainfield',
    'Streamwood',
    'Carol Stream',
    'Romeoville',
    'Rock Island',
    'Hanover Park',
    'Carpentersville',
    'Wheeling',
    'Park Ridge',
    'Addison',
    'Calumet City',
    //Texas
    'Houston',
    'San Antonio',
    'Dallas',
    'Austin',
    'Fort Worth',
    'El Paso',
    'Arlington',
    'Corpus Christi',
    'Plano',
    'Laredo',
    'Lubbock',
    'Garland',
    'Irving',
    'Amarillo',
    'Grand Prairie',
    'Brownsville',
    'Pasadena',
    'McKinney',
    'Mesquite',
    'McAllen',
    'Killeen',
    'Frisco',
    'Waco',
    'Carrollton',
    'Denton',
    'Midland',
    'Abilene',
    'Beaumont',
    'Round Rock',
    'Odessa',
    'Wichita Falls',
    'Richardson',
    'Lewisville',
    'Tyler',
    'College Station',
    'Pearland',
    'San Angelo',
    'Allen',
    'League City',
    'Sugar Land',
    'Longview',
    'Edinburg',
    'Mission',
    'Bryan',
    'Baytown',
    'Pharr',
    'Temple',
    'Missouri City',
    'Flower Mound',
    'Harlingen',
    'North Richland Hills',
    'Victoria',
    'Conroe',
    'New Braunfels',
    'Mansfield',
    'Cedar Park',
    'Rowlett',
    'Port Arthur',
    'Euless',
    'Georgetown',
    'Pflugerville',
    'DeSoto',
    'San Marcos',
    'Grapevine',
    'Bedford',
    'Galveston',
    'Cedar Hill',
    'Texas City',
    'Wylie',
    'Haltom City',
    'Keller',
    'Coppell',
    'Rockwall',
    'Huntsville',
    'Duncanville',
    'Sherman',
    'The Colony',
    'Burleson',
    'Hurst',
    'Lancaster',
    'Texarkana',
    'Friendswood',
    'Weslaco',
    //Pennsylvania
    'Philadelphia',
    'Pittsburgh',
    'Allentown',
    'Erie',
    'Reading',
    'Scranton',
    'Bethlehem',
    'Lancaster',
    'Harrisburg',
    'Altoona',
    'York',
    'State College',
    'Wilkes-Barre',
    //Arizona
    'Phoenix',
    'Tucson',
    'Mesa',
    'Chandler',
    'Glendale',
    'Scottsdale',
    'Gilbert',
    'Tempe',
    'Peoria',
    'Surprise',
    'Yuma',
    'Avondale',
    'Goodyear',
    'Flagstaff',
    'Buckeye',
    'Lake Havasu City',
    'Casa Grande',
    'Sierra Vista',
    'Maricopa',
    'Oro Valley',
    'Prescott',
    'Bullhead City',
    'Prescott Valley',
    'Marana',
    'Apache Junction',
    //Florida
    'Jacksonville',
    'Miami',
    'Tampa',
    'Orlando',
    'St. Petersburg',
    'Hialeah',
    'Tallahassee',
    'Fort Lauderdale',
    'Port St. Lucie',
    'Cape Coral',
    'Pembroke Pines',
    'Hollywood',
    'Miramar',
    'Gainesville',
    'Coral Springs',
    'Miami Gardens',
    'Clearwater',
    'Palm Bay',
    'Pompano Beach',
    'West Palm Beach',
    'Lakeland',
    'Davie',
    'Miami Beach',
    'Sunrise',
    'Plantation',
    'Boca Raton',
    'Deltona',
    'Largo',
    'Deerfield Beach',
    'Palm Coast',
    'Melbourne',
    'Boynton Beach',
    'Lauderhill',
    'Weston',
    'Fort Myers',
    'Kissimmee',
    'Homestead',
    'Tamarac',
    'Delray Beach',
    'Daytona Beach',
    'North Miami',
    'Wellington',
    'North Port',
    'Jupiter',
    'Ocala',
    'Port Orange',
    'Margate',
    'Coconut Creek',
    'Sanford',
    'Sarasota',
    'Pensacola',
    'Bradenton',
    'Palm Beach Gardens',
    'Pinellas Park',
    'Coral Gables',
    'Doral',
    'Bonita Springs',
    'Apopka',
    'Titusville',
    'North Miami Beach',
    'Oakland Park',
    'Fort Pierce',
    'North Lauderdale',
    'Cutler Bay',
    'Altamonte Springs',
    'St. Cloud',
    'Greenacres',
    'Ormond Beach',
    'Ocoee',
    'Hallandale Beach',
    'Winter Garden',
    'Aventura',
    //Indiana
    'Indianapolis',
    'Fort Wayne',
    'Evansville',
    'South Bend',
    'Carmel',
    'Bloomington',
    'Fishers',
    'Hammond',
    'Gary',
    'Muncie',
    'Lafayette',
    'Terre Haute',
    'Kokomo',
    'Anderson',
    'Noblesville',
    'Greenwood',
    'Elkhart',
    'Mishawaka',
    'Lawrence',
    'Jeffersonville',
    'Columbus',
    'Portage',
    //Ohio
    'Columbus',
    'Cleveland',
    'Cincinnati',
    'Toledo',
    'Akron',
    'Dayton',
    'Parma',
    'Canton',
    'Youngstown',
    'Lorain',
    'Hamilton',
    'Springfield',
    'Kettering',
    'Elyria',
    'Lakewood',
    'Cuyahoga Falls',
    'Middletown',
    'Euclid',
    'Newark',
    'Mansfield',
    'Mentor',
    'Beavercreek',
    'Cleveland Heights',
    'Strongsville',
    'Dublin',
    'Fairfield',
    'Findlay',
    'Warren',
    'Lancaster',
    'Lima',
    'Huber Heights',
    'Westerville',
    'Marion',
    'Grove City',
    //North Carolina
    'Charlotte',
    'Raleigh',
    'Greensboro',
    'Durham',
    'Winston-Salem',
    'Fayetteville',
    'Cary',
    'Wilmington',
    'High Point',
    'Greenville',
    'Asheville',
    'Concord',
    'Gastonia',
    'Jacksonville',
    'Chapel Hill',
    'Rocky Mount',
    'Burlington',
    'Wilson',
    'Huntersville',
    'Kannapolis',
    'Apex',
    'Hickory',
    'Goldsboro',
    //Michigan
    'Detroit',
    'Grand Rapids',
    'Warren',
    'Sterling Heights',
    'Ann Arbor',
    'Lansing',
    'Flint',
    'Dearborn',
    'Livonia',
    'Westland',
    'Troy',
    'Farmington Hills',
    'Kalamazoo',
    'Wyoming',
    'Southfield',
    'Rochester Hills',
    'Taylor',
    'Pontiac',
    'St. Clair Shores',
    'Royal Oak',
    'Novi',
    'Dearborn Heights',
    'Battle Creek',
    'Saginaw',
    'Kentwood',
    'East Lansing',
    'Roseville',
    'Portage',
    'Midland',
    'Lincoln Park',
    'Muskegon',
    //Tennessee
    'Memphis',
    'Nashville',
    'Knoxville',
    'Chattanooga',
    'Clarksville',
    'Murfreesboro',
    'Jackson',
    'Franklin',
    'Johnson City',
    'Bartlett',
    'Hendersonville',
    'Kingsport',
    'Collierville',
    'Cleveland',
    'Smyrna',
    'Germantown',
    'Brentwood',
    //Massachusetts
    'Boston',
    'Worcester',
    'Springfield',
    'Lowell',
    'Cambridge',
    'New Bedford',
    'Brockton',
    'Quincy',
    'Lynn',
    'Fall River',
    'Newton',
    'Lawrence',
    'Somerville',
    'Waltham',
    'Haverhill',
    'Malden',
    'Medford',
    'Taunton',
    'Chicopee',
    'Weymouth Town',
    'Revere',
    'Peabody',
    'Methuen',
    'Barnstable Town',
    'Pittsfield',
    'Attleboro',
    'Everett',
    'Salem',
    'Westfield',
    'Leominster',
    'Fitchburg',
    'Beverly',
    'Holyoke',
    'Marlborough',
    'Woburn',
    'Chelsea',
    //Washington
    'Seattle',
    'Spokane',
    'Tacoma',
    'Vancouver',
    'Bellevue',
    'Kent',
    'Everett',
    'Renton',
    'Yakima',
    'Federal Way',
    'Spokane Valley',
    'Bellingham',
    'Kennewick',
    'Auburn',
    'Pasco',
    'Marysville',
    'Lakewood',
    'Redmond',
    'Shoreline',
    'Richland',
    'Kirkland',
    'Burien',
    'Sammamish',
    'Olympia',
    'Lacey',
    'Edmonds',
    'Bremerton',
    'Puyallup',
    //Colorado
    'Denver',
    'Colorado Springs',
    'Aurora',
    'Fort Collins',
    'Lakewood',
    'Thornton',
    'Arvada',
    'Westminster',
    'Pueblo',
    'Centennial',
    'Boulder',
    'Greeley',
    'Longmont',
    'Loveland',
    'Grand Junction',
    'Broomfield',
    'Castle Rock',
    'Commerce City',
    'Parker',
    'Littleton',
    'Northglenn',
    //District of Columbia
    'Washington',
    //Maryland
    'Baltimore',
    'Frederick',
    'Rockville',
    'Gaithersburg',
    'Bowie',
    'Hagerstown',
    'Annapolis',
    //Kentucky
    'Louisville',
    'Lexington',
    'Bowling Green',
    'Owensboro',
    'Covington',
    //Oregon
    'Portland',
    'Eugene',
    'Salem',
    'Gresham',
    'Hillsboro',
    'Beaverton',
    'Bend',
    'Medford',
    'Springfield',
    'Corvallis',
    'Albany',
    'Tigard',
    'Lake Oswego',
    'Keizer',
    //Oklahoma
    'Oklahoma City',
    'Tulsa',
    'Norman',
    'Broken Arrow',
    'Lawton',
    'Edmond',
    'Moore',
    'Midwest City',
    'Enid',
    'Stillwater',
    'Muskogee',
    //Wisconsin
    'Milwaukee',
    'Madison',
    'Green Bay',
    'Kenosha',
    'Racine',
    'Appleton',
    'Waukesha',
    'Eau Claire',
    'Oshkosh',
    'Janesville',
    'West Allis',
    'La Crosse',
    'Sheboygan',
    'Wauwatosa',
    'Fond du Lac',
    'New Berlin',
    'Wausau',
    'Brookfield',
    'Greenfield',
    'Beloit',
    //Nevada
    'Las Vegas',
    'Henderson',
    'Reno',
    'North Las Vegas',
    'Sparks',
    'Carson City',
    //New Mexico
    'Albuquerque',
    'Las Cruces',
    'Rio Rancho',
    'Santa Fe',
    'Roswell',
    'Farmington',
    'Clovis',
    //Missouri
    'Kansas City',
    'St.Louis',
    'Springfield',
    'Independence',
    'Columbia',
    'Lees Summit',
    'O Fallon',
    'St Joseph',
    'St Charles',
    'St Peters',
    'Blue Springs',
    'Florissant',
    'Joplin',
    'Chesterfield',
    'Jefferson City',
    'Cape Girardeau',
    //Virginia
    'Virginia Beach',
    'Norfolk',
    'Chesapeake',
    'Richmond',
    'Newport News',
    'Alexandria',
    'Hampton',
    'Roanoke',
    'Portsmouth',
    'Suffolk',
    'Lynchburg',
    'Harrisonburg',
    'Leesburg',
    'Charlottesville',
    'Danville',
    'Blacksburg',
    'Manassas',
    //Georgia
    'Atlanta',
    'Columbus',
    'Augusta',
    'Savannah',
    'Athens',
    'Sandy Springs',
    'Roswell',
    'Macon',
    'Johns Creek',
    'Albany',
    'Warner Robins',
    'Alpharetta',
    'Marietta',
    'Valdosta',
    'Smyrna',
    'Dunwoody',
    //Nebraska
    'Omaha',
    'Lincoln',
    'Bellevue',
    'Grand Island',
    //Minnesota
    'Minneapolis',
    'St Paul',
    'Rochester',
    'Duluth',
    'Bloomington',
    'Brooklyn Park',
    'Plymouth',
    'St Cloud',
    'Eagan',
    'Woodbury',
    'Maple Grove',
    'Eden Prairie',
    'Coon Rapids',
    'Burnsville',
    'Blaine',
    'Lakeville',
    'Minnetonka',
    'Apple Valley',
    'Edina',
    'St Louis Park',
    'Mankato',
    'Maplewood',
    'Moorhead',
    'Shakopee',
    //Kansas
    'Wichita',
    'Overland Park',
    'Kansas City',
    'Olathe',
    'Topeka',
    'Lawrence',
    'Shawnee',
    'Manhattan',
    'Lenexa',
    'Salina',
    'Hutchinson',
    //Louisiana
    'New Orleans',
    'Baton Rouge',
    'Shreveport',
    'Lafayette',
    'Lake Charles',
    'Kenner',
    'Bossier City',
    'Monroe',
    'Alexandria',
    //Hawaii
    'Honolulu',
    //Alaska
    'Anchorage',
    //New Jersey
    'Newark',
    'Jersey City',
    'Paterson',
    'Elizabeth',
    'Clifton',
    'Trenton',
    'Camden',
    'Passaic',
    'Union City',
    'Bayonne',
    'East Orange',
    'Vineland',
    'New Brunswick',
    'Hoboken',
    'Perth Amboy',
    'West New York',
    'Plainfield',
    'Hackensack',
    'Sayreville',
    'Kearny',
    'Linden',
    'Atlantic City',
//Idaho
    'Boise City',
    'Nampa',
    'Meridian',
    'Idaho Falls',
    'Pocatello',
    'Caldwell',
    'Coeur d Alene',
    'Twin Falls',
    //Alabama
    'Birmingham',
    'Montgomery',
    'Mobile',
    'Huntsville',
    'Tuscaloosa',
    'Hoover',
    'Dothan',
    'Auburn',
    'Decatur',
    'Madison',
    'Florence',
    'Gadsden',
    //Iowa
    'Des Moines',
    'Cedar Rapids',
    'Davenport',
    'Sioux City',
    'Iowa City',
    'Waterloo',
    'Council Bluffs',
    'Ames',
    'West Des Moines',
    'Dubuque',
    'Ankeny',
    'Urbandale',
    'Cedar Falls',
    //Arkansas
    'Little Rock',
    'Fort Smith',
    'Fayetteville',
    'Springdale',
    'Jonesboro',
    'North Little Rock',
    'Conway',
    'Rogers',
    'Pine Bluff',
    'Bentonville',
    //Utah
    'Salt Lake City',
    'West Valley City',
    'Provo',
    'West Jordan',
    'Orem',
    'Sandy',
    'Ogden',
    'St George',
    'Layton',
    'Taylorsville',
    'South Jordan',
    'Lehi',
    'Logan',
    'Murray',
    'Draper',
    'Bountiful',
    'Riverton',
    'Roy',
    //Rhode Island
    'Providence',
    'Warwick',
    'Cranston',
    'Pawtucket',
    'East Providence',
    'Woonsocket',
    //Mississippi
    'Jackson',
    'Gulfport',
    'Southaven',
    'Hattiesburg',
    'Biloxi',
    'Meridian',
    //South Dakota
    'Sioux Falls',
    'Rapid City',
    //Connecticut
    'Bridgeport',
    'New Haven',
    'Stamford',
    'Hartford',
    'Waterbury',
    'Norwalk',
    'Danbury',
    'New Britain',
    'Meriden',
    'Bristol',
    'West Haven',
    'Milford',
    'Middletown',
    'Norwich',
    'Shelton',
    //South Carolina
    'Columbia',
    'Charleston',
    'North Charleston',
    'Mount Pleasant',
    'Rock Hill',
    'Greenville',
    'Summerville',
    'Sumter',
    'Goose Creek',
    'Hilton Head Island',
    'Florence',
    'Spartanburg',
    //New Hampshire
    'Manchester',
    'Nashua',
    'Concord',
    //North Dakota
    'Fargo',
    'Bismarck',
    'Grand Forks',
    'Minot',
    //Montana
    'Billings',
    'Missoula',
    'Great Falls',
    'Bozeman',
    //Delaware
    'Wilmington',
    'Dover',
    //Maine
    'Portland',
    //Wyoming
    'Cheyenne',
    'Casper',
    //West Virginia
    'Charleston',
    'Huntington',
    //Vermont
    'Burlington'
];